site_name: TopoPyScale
site_url: https://example.com/
site_author: Simon Filhol, Joel Fiddes
copyright: GNU GPL3
nav:
    - Home: index.md
    - Quick Start: quickstart.md
    - Project Configuration: configFile.md
    - About: about.md
theme: material
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
