site_name: TopoPyScale
site_url: https://example.com/
site_author: Simon Filhol, Joel Fiddes
copyright: GNU GPL3
nav:
    - Home: 0_index.md
    - Installation: 1_instal.md
    - Quick Start: 2_quickstart.md
    - Project Configuration: 3_configurationFile.md
    - Datasets: 4_datasetSources.md
    - Outputs: 5_models.md
    - API:
        - topoclass: TopoPyScale.topoclass.md
        - topo_sub: TopoPyScale.topo_sub.md
        - topo_scale: TopoPyScale.topo_scale.md
        - solar_geom: TopoPyScale.solar_geom.md
        - topo_param: TopoPyScale.topo_param.md
        - fetch_era5: TopoPyScale.fetch_era5.md
        - fetch_dem: TopoPyScale.fetch_dem.md
        - meteo_util: TopoPyScale.meteo_util.md
        - topo_sim: TopoPyScale.topo_sim.md
        - topo_export: TopoPyScale.topo_export.md
        - topo_da: TopoPyScale.topo_da.md
        - topo_obs: TopoPyScale.topo_obs.md
        - topo_utils: TopoPyScale.topo_utils.md
        - topo_compare: TopoPyScale.topo_compare.md
        - topo_plot: TopoPyScale.topo_plot.md


theme: material
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
